services:
  server:
    image: pk-backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    environment:
      - MONGODB_URI=MONGO_URI
      - PORT=3001
    volumes:
      - ./backend/:/usr/src/app
    container_name: pk-server-dev

  app:
    image: pk-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=/api/
    volumes:
      - ./frontend/:/usr/src/app
    container_name: pk-frontend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: pk-reverse-proxy
    depends_on:
      - server
      - app
