services:
  server:
    image: pk-backend-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=MONGO_URI
      - PORT=3001
    volumes:
      - ./backend/:/usr/src/app
    container_name: pk-server-prod

  app:
    image: pk-frontend-prod
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    container_name: pk-frontend-prod


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: pk-reverse-proxy
    depends_on:
      - server
      - app
